### ISSUE TITLE
Panic when running job

### ISSUE THREAD

**Issue by seiffert** [victorcoder/dkron#110]
Hi,

we're currently experiencing a panic when manually running a job:

```
2016/04/26 16:11:13 http: panic serving 10.8.1.217:62544: runtime error: invalid memory address or nil pointer dereference
goroutine 622306 [running]:
net/http.(*conn).serve.func1(0xc8205866e0, 0x7f90b738adc0, 0xc820022168)
/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1287 +0xb5
github.com/victorcoder/dkron/vendor/github.com/hashicorp/serf/serf.(*QueryResponse).Close(0x0)
/Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/hashicorp/serf/serf/query.go:117 +0xe7
github.com/victorcoder/dkron/dkron.(*AgentCommand).RunQuery(0xc820122120, 0xc820206f00)
/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:723 +0xe49
github.com/victorcoder/dkron/dkron.(*AgentCommand).jobRunHandler(0xc820122120, 0x7f90b738b580, 0xc82013f810, 0xc8201be0e0)
/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/api.go:213 +0x2e7
github.com/victorcoder/dkron/dkron.(*AgentCommand).(github.com/victorcoder/dkron/dkron.jobRunHandler)-fm(0x7f90b738b580, 0xc82013f810, 0xc8201be0e0)
/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/api.go:63 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc82020b600, 0x7f90b738b580, 0xc82013f810, 0xc8201be0e0)
/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
github.com/victorcoder/dkron/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000cd70, 0x7f90b738b580, 0xc82013f810, 0xc8201be0e0)
/Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).UseHandler.func1.1(0x7f90b738b580, 0xc82013f810, 0xc8201be0e0)
/Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:55 +0x69
net/http.HandlerFunc.ServeHTTP(0xc8200f2150, 0x7f90b738b580, 0xc82013f810, 0xc8201be0e0)
/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
github.com/victorcoder/dkron/dkron.metaMiddleware.func1.1(0x7f90b738b580, 0xc82013f810, 0xc8201be0e0)
/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/api.go:78 +0x1ac
net/http.HandlerFunc.ServeHTTP(0xc8200f2180, 0x7f90b738b580, 0xc82013f810, 0xc8201be0e0)
/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1422 +0x3a
github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).ServeHTTP(0xc820210fa0, 0x7f90b738b580, 0xc82013f810, 0xc8201be0e0)
/Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:85 +0x6c
net/http.serverHandler.ServeHTTP(0xc820015e60, 0x7f90b738b580, 0xc82013f810, 0xc8201be0e0)
/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8205866e0)
/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.5/libexec/src/net/http/server.go:1910 +0x3f6
```

I've tracked the error down to these lines of code: ([link](https://github.com/victorcoder/dkron/blob/52c7a5749e9aa9192e3967dcaa26307a1e4c4719/dkron/agent.go#L715-L720))

```go
	qr, err := a.serf.Query(QueryRunJob, exJson, params)
	if err != nil {
		log.WithFields(logrus.Fields{
			"query": QueryRunJob,
			"error": err,
		}).Debug("agent: Sending query error")
	}
	defer qr.Close()
```

From my perspective, the error is not being handled properly. The `qr.Close` is then called on `nil` which breaks somewhere in serf.

**Comment by seiffert** [comment]
After enabling debug logging, I found out that the error's root cause is probably a job description that is too large: 

```
time="2016-04-26T16:36:29Z" level=debug msg="agent: Sending query error" error="query exceeds limit of 1024 bytes" node=ip-10-8-3-112.eu-west-1.compute.internal query="run:job"
```

Still, this error should be handled.

Is there maybe also a way to validate the job description size and catch this error before? Or even better: Could this size limit be increased?

**Comment by victorcoder** [comment]
Hi @seiffert, sadly the limit can't be increased due to serf internals https://groups.google.com/forum/#!topic/serfdom/rqiFFNIOOhI

What do you mean a "job description"? 

It should be handled and validated, it's probably caused by the serf query being oversized as you say.

Could you paste the job or a sample here?

**Comment by seiffert** [comment]
Oh with job description I meant the job's command. Sadly, I can't paste the used command in here, but the command string has 11484 characters. I know that this is not the usual case (also not in our company), but it happens and it would be good to make the limits explicit.

**Comment by seiffert** [comment]
Would it maybe be an option to pass around the job's identifier via serf instead of the whole job? This way the command size wouldn't be a problem and AFAIK all nodes can access the store to fetch a job by its name.

**Comment by victorcoder** [comment]
@seiffert that's not an option, I've a strong requirement that client nodes doesn't need to see/access the store.

I'm going to warn and make the limit explicit and not panic.

**Comment by seiffert** [comment]
Ok that's a good first step 😉  Should we also transform the `Debug` logging in the [above-mentioned line](https://github.com/victorcoder/dkron/blob/52c7a5749e9aa9192e3967dcaa26307a1e4c4719/dkron/agent.go#L715-L720) into a `Fatal` logging (after bringing the validation in place)?
