### ISSUE TITLE
Agent crashes after setting key in ZK backend

### ISSUE THREAD

**Issue by kennydo** [victorcoder/dkron#195]
I added a simple job that just runs `/usr/bin/uptime`.

When I click "Run" on the UI, I get the message "Error running job test-kedo-01" in the UI, but I see that it actually did run in the log output:
```
DEBU[2016-09-27T18:05:03Z] store: Retrieved job from datastore           job=test-kedo-01 node=ip-172-31-8-0
DEBU[2016-09-27T18:05:03Z] store: Retrieved job from datastore           job=test-kedo-01 node=ip-172-31-8-0
DEBU[2016-09-27T18:05:03Z] agent: Filtered nodes to run: []              node=ip-172-31-8-0
DEBU[2016-09-27T18:05:03Z] agent: Filtered tags to run: map[]            node=ip-172-31-8-0
DEBU[2016-09-27T18:05:03Z] agent: Sending query                          job_name=test-kedo-01 json={"execution":{"job_name":"test-kedo-01","started_at":"0001-01-01T00:00:00Z","finished_at":"0001-01-01T00:00:00Z","group":1474999503637733022,"attempt":1},"rpc_addr":"172.31.8.0:6868"} node=ip-172-31-8-0 query=run:job
DEBU[2016-09-27T18:05:03Z] agent: Received event                         event=query: run:job node=ip-172-31-8-0
DEBU[2016-09-27T18:05:03Z] agent: Running job                            at=7561 node=ip-172-31-8-0 payload={"execution":{"job_name":"test-kedo-01","started_at":"0001-01-01T00:00:00Z","finished_at":"0001-01-01T00:00:00Z","group":1474999503637733022,"attempt":1},"rpc_addr":"172.31.8.0:6868"} query=run:job
DEBU[2016-09-27T18:05:03Z] agent: Received ack                           from=ip-172-31-8-0 node=ip-172-31-8-0 query=run:job
INFO[2016-09-27T18:05:03Z] agent: Starting job                           job=test-kedo-01 node=ip-172-31-8-0
DEBU[2016-09-27T18:05:03Z] rpc: Received GetJob                          job=test-kedo-01 node=ip-172-31-8-0
DEBU[2016-09-27T18:05:03Z] store: Retrieved job from datastore           job=test-kedo-01 node=ip-172-31-8-0
DEBU[2016-09-27T18:05:03Z] agent: GetJob by RPC                          command=/usr/bin/uptime node=ip-172-31-8-0
DEBU[2016-09-27T18:05:03Z] agent: Received response                      from=ip-172-31-8-0 node=ip-172-31-8-0 query=run:job response={"job_name":"test-kedo-01","started_at":"2016-09-27T18:05:03.640169984Z","finished_at":"0001-01-01T00:00:00Z","node_name":"ip-172-31-8-0","group":1474999503637733022,"attempt":1}
DEBU[2016-09-27T18:05:03Z] store: Setting key                            execution=1474999503640169984-ip-172-31-8-0 job=test-kedo-01 node=ip-172-31-8-0
DEBU[2016-09-27T18:05:03Z] proc: Command output                          node=ip-172-31-8-0 output= 18:05:03 up 3 days, 22:57,  1 user,  load average: 0.00, 0.01, 0.05

2016/09/27 18:05:03 http: panic serving 172.31.8.241:63066: runtime error: index out of range
goroutine 59 [running]:
net/http.(*conn).serve.func1(0xc82012b080)
	/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:1389 +0xc1
panic(0xbb9dc0, 0xc820010010)
	/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/runtime/panic.go:443 +0x4e9
github.com/victorcoder/dkron/dkron.(*Store).GetExecutions(0xc8201b2330, 0xc820010f40, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/store.go:243 +0x588
github.com/victorcoder/dkron/dkron.(*Store).SetExecution(0xc8201b2330, 0xc820084100, 0x0, 0x0, 0x0, 0x0)
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/store.go:329 +0x674
github.com/victorcoder/dkron/dkron.(*AgentCommand).setExecution(0xc8201421e0, 0xc8200cc780, 0xb2, 0xb2, 0xc820010300)
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:602 +0x180
github.com/victorcoder/dkron/dkron.(*AgentCommand).RunQuery(0xc8201421e0, 0xc82012a980)
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/queries.go:92 +0x15e6
github.com/victorcoder/dkron/dkron.(*AgentCommand).jobRunHandler(0xc8201421e0, 0x7f5c4dd59438, 0xc8201328f0, 0xc8207fa380)
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/api.go:243 +0x30d
github.com/victorcoder/dkron/dkron.(*AgentCommand).(github.com/victorcoder/dkron/dkron.jobRunHandler)-fm(0x7f5c4dd59438, 0xc8201328f0, 0xc8207fa380)
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/api.go:63 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820123940, 0x7f5c4dd59438, 0xc8201328f0, 0xc8207fa380)
	/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:1618 +0x3a
github.com/victorcoder/dkron/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82012c5f0, 0x7f5c4dd59438, 0xc8201328f0, 0xc8207fa380)
	/Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).UseHandler.func1.1(0x7f5c4dd59438, 0xc8201328f0, 0xc8207fa380)
	/Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:55 +0x69
net/http.HandlerFunc.ServeHTTP(0xc82020ddd0, 0x7f5c4dd59438, 0xc8201328f0, 0xc8207fa380)
	/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:1618 +0x3a
github.com/victorcoder/dkron/dkron.metaMiddleware.func1.1(0x7f5c4dd59438, 0xc8201328f0, 0xc8207fa380)
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/api.go:78 +0x1ac
net/http.HandlerFunc.ServeHTTP(0xc82020de00, 0x7f5c4dd59438, 0xc8201328f0, 0xc8207fa380)
	/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:1618 +0x3a
github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose.(*Middleware).ServeHTTP(0xc8201ce220, 0x7f5c4dd59438, 0xc8201328f0, 0xc8207fa380)
	/Users/victorcoder/src/github.com/victorcoder/dkron/vendor/github.com/carbocation/interpose/interpose.go:85 +0x6c
net/http.serverHandler.ServeHTTP(0xc82012ae00, 0x7f5c4dd59438, 0xc8201328f0, 0xc8207fa380)
	/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82012b080)
	/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/net/http/server.go:2137 +0x44e
```

When I look at my zookeeper exhibitor, I see that the execution key `1474999503720835723-ip-172-31-8-0` was created, so I suspect that sometime errors afterwards.

Here are the relevant parts of my `dkron.json`:
```
...
  "backend": "zk",
  "backend_machine": [
    "zookeeper.internal:2181"
  ],
  "server": true,
  "debug": true,
  "log_level": "debug",
...
```

I already upgraded to 0.9.1 to pick up the zookeeper fixes.
Any idea what's wrong?

**Comment by kennydo** [comment]
Whoops, I just realized that I typo-d and didn't actually install 0.9.1.

0.9.1 works great! Thanks for the good work!
