### ISSUE TITLE
"Invalid memory address or nil pointer dereference" error

### ISSUE THREAD

**Issue by greggilbert** [victorcoder/dkron#202]
Hey. I've got a bunch of instances running dkron with a Consul cluster as their backing store. I'm trying to update from Dkron 0.7 to 0.9.1. The instances that are running 0.9.1 throw this error:

```
time="2016-10-25T14:52:07-04:00" level=info msg="agent: Listen for events" node=ip-10-0-15-163
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x48897c]

goroutine 50 [running]:
panic(0xbb9dc0, 0xc820010060)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/victorcoder/dkron/dkron.(*AgentCommand).eventLoop(0xc82000c4e0)
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:490 +0x1abc
created by github.com/victorcoder/dkron/dkron.(*AgentCommand).Run
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:298 +0x362
Starting Dkron agent...
time="2016-10-25T14:52:07-04:00" level=info msg="agent: Dkron agent starting" node=ip-10-0-15-163
```

I'm not doing anything crazy here, I don't think. It's been working for months. Any ideas?

More debug:

```
// /etc/dkron/dkron.json
{
  "backend": "consul",
  "backend_machine": "consul.internal:8500",
  "keyspace": "bkg-process",
  "http_addr": ":8988",
  "server": true,
  "encrypt": "KEY",
  "tags": {
    "role": "background_processing"
  },
  "join": "background-processing.service.dc1.consul"
}
```

```
$ curl 127.0.0.1:8988/v1/jobs
[{"name":"cron_job","schedule":"0 * * * * *","shell":false,"command":"/queue.sh","owner":"Me,"owner_email":"me@me.com","success_count":254066,"error_count":0,"last_success":"2016-10-25T15:00:00.23316342-04:00","last_error":"0001-01-01T00:00:00Z","disabled":false,"tags":{"role":"background_processing:1"},"retries":0,"dependent_jobs":null,"parent_job":""}]
```

**Comment by victorcoder** [comment]
As you reference in #204 could it be that you end up with an old leader key lock in consul. 

Could it be related to this note? https://github.com/victorcoder/dkron/blob/master/CHANGELOG.md#upgrade-from-06x

Even with a running cluster if you remove the leader key it should fire up the leader election routine and write a TTL based leader key in consul.

**Comment by greggilbert** [comment]
I was on 0.7.1 before, but the changelog note indicates that it should only be an issue in 0.6 -> 0.7. And we were seeing the issue in #204 with version 0.7.1, so I don't think it's totally related.

**Comment by victorcoder** [comment]
@greggilbert this is a tricky error, could you try to upgrade one of the failing nodes to `0.7.3` first and see if it works?

**Comment by greggilbert** [comment]
@victorcoder I took the failing node out of rotation and put in one with `0.7.3` on it, and I haven't seen any issues yet with it. Does that help?

**Comment by greggilbert** [comment]
Actually, questions related to the leader key: 

1. Should the leader key always be the same node that ran the last job? 
2. Is the leader key supposed to expire after a certain period of time?

**Comment by victorcoder** [comment]
> I took the failing node out of rotation and put in one with 0.7.3 on it, and I haven't seen any issues yet with it. Does that help?

@greggilbert yes it does! Now can you try to upgrade the node to 0.9.1?

> 1. Should the leader key always be the same node that ran the last job?

Not necessarily but the leader is the node that run jobs.

> 2. Is the leader key supposed to expire after a certain period of time?

This is handled transparently by consul in your case but it only expires if the dkron cluster is offline.

**Comment by greggilbert** [comment]
> @greggilbert yes it does! Now can you try to upgrade the node to 0.9.1?

Done - and it seems to work. Or at least it's not throwing any errors. Did it have to do some sort of internal migration to catch up the version? Can I bring up some nodes now that have 0.9.1 by default, or do I need to do this 0.7.3 -> 0.9.1 path on all of them?

**Comment by victorcoder** [comment]
@greggilbert I don't know exactly which was the change that forces the upgrade path, but I recommend you to upgrade to 0.7.3 -> 0.9.1 on all nodes.

Anyway, I'll add a note in the documentation.

**Comment by greggilbert** [comment]
@victorcoder: wait, sorry, I spoke too soon. The upgraded version threw the same error:

```
time="2016-10-26T17:13:07-04:00" level=info msg="api: Running HTTP server" address=":8988" node=ip-10-0-16-8
time="2016-10-26T17:13:07-04:00" level=info msg="agent: Running for election" node=ip-10-0-16-8
time="2016-10-26T17:13:07-04:00" level=info msg="agent: Cluster leadership lost" node=ip-10-0-16-8
time="2016-10-26T17:13:07-04:00" level=info msg="agent: Listen for events" node=ip-10-0-16-8
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x48897c]

goroutine 7 [running]:
panic(0xbb9dc0, 0xc820010060)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/victorcoder/dkron/dkron.(*AgentCommand).eventLoop(0xc820050480)
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:490 +0x1abc
created by github.com/victorcoder/dkron/dkron.(*AgentCommand).Run
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:298 +0x362
Starting Dkron agent...
time="2016-10-26T17:13:07-04:00" level=info msg="agent: Dkron agent starting" node=ip-10-0-16-8
time="2016-10-26T17:13:07-04:00" level=info msg="agent: joining: [background-processing.service.dc1.consul] replay: true" node=ip-10-0-16-8
time="2016-10-26T17:13:07-04:00" level=info msg="agent: joined: 3 nodes" node=ip-10-0-16-8
time="2016-10-26T17:13:07-04:00" level=info msg="api: Running HTTP server" address=":8988" node=ip-10-0-16-8
time="2016-10-26T17:13:07-04:00" level=info msg="agent: Running for election" node=ip-10-0-16-8
time="2016-10-26T17:13:07-04:00" level=info msg="agent: Cluster leadership lost" node=ip-10-0-16-8
time="2016-10-26T17:13:07-04:00" level=info msg="agent: Listen for events" node=ip-10-0-16-8
```

Can you reopen this?

**Comment by greggilbert** [comment]
@victorcoder ping on this, sorry. Can we reopen?

**Comment by victorcoder** [comment]
@greggilbert are they crashing with 0.7.3 also or just when upgrading to 0.9.1?

**Comment by victorcoder** [comment]
@greggilbert could you run the failing node setting `log_level=debug`in config? Then paste the relevant bits here removing sensitive info, this should throw some light.

**Comment by greggilbert** [comment]
Sure, I'll get back to you on this tomorrow.

**Comment by greggilbert** [comment]
Ugh, I totally forgot to get back to you on this. I'm going to try to free up some time in the next week to look at it. Sorry about the wait! :[

**Comment by greggilbert** [comment]
Okay - I'm back, finally. Sorry about that. Here's the logs with `level=debug`.

```
time="2016-12-01T11:52:00-05:00" level=debug msg="agent: Received event" event="query: run:job" node=ip-INSTANCE
time="2016-12-01T11:52:00-05:00" level=debug msg="agent: Running job" at=229819 node=ip-INSTANCE payload="{\"job_name\":\"cron_job\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1480611120000410091,\"job
\":{\"name\":\"cron_job\",\"schedule\":\"0 * * * * *\",\"command\":\"/cron-worker-queue.sh\",\"owner\":\"OWNER\",\"owner_email\":\"USER@DOMAIN.com\",\"run_as_user\":\"\",\"success_count\":303585,\"error_count\":0,\"last_success\":\"2016-11
-30T18:06:00.369454892-05:00\",\"last_error\":\"0001-01-01T00:00:00Z\",\"disabled\":false,\"tags\":{\"role\":\"background_processing:1\"}}}" query="run:job"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x48897c]

goroutine 43 [running]:
panic(0xbb9dc0, 0xc820010060)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/victorcoder/dkron/dkron.(*AgentCommand).eventLoop(0xc82013e1e0)
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:490 +0x1abc
created by github.com/victorcoder/dkron/dkron.(*AgentCommand).Run
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:298 +0x362
Starting Dkron agent...
time="2016-12-01T11:52:00-05:00" level=info msg="agent: Dkron agent starting" node=ip-INSTANCE
time="2016-12-01T11:52:00-05:00" level=info msg="agent: joining: [background-processing.service.dc1.consul] replay: true" node=ip-INSTANCE
time="2016-12-01T11:52:00-05:00" level=info msg="agent: joined: 3 nodes" node=ip-INSTANCE
time="2016-12-01T11:52:00-05:00" level=debug msg="store: Backend config" backend=consul keyspace=bkg-process machines=[consul.internal.OWNER:8500] node=ip-INSTANCE
time="2016-12-01T11:52:00-05:00" level=info msg="api: Running HTTP server" address=":8988" node=ip-INSTANCE
time="2016-12-01T11:52:00-05:00" level=debug msg="rpc: Registering RPC server" node=ip-INSTANCE rpc_addr="INSTANCE:6868"
time="2016-12-01T11:52:00-05:00" level=info msg="agent: Running for election" node=ip-INSTANCE
time="2016-12-01T11:52:00-05:00" level=info msg="agent: Cluster leadership lost" node=ip-INSTANCE
time="2016-12-01T11:52:00-05:00" level=info msg="agent: Listen for events" node=ip-INSTANCE
time="2016-12-01T11:52:00-05:00" level=debug msg="agent: Received event" event="query: run:job" node=ip-INSTANCE
time="2016-12-01T11:52:00-05:00" level=debug msg="agent: Running job" at=229819 node=ip-INSTANCE payload="{\"job_name\":\"cron_job\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1480611120000410091,\"job
\":{\"name\":\"cron_job\",\"schedule\":\"0 * * * * *\",\"command\":\"/cron-worker-queue.sh\",\"owner\":\"OWNER\",\"owner_email\":\"USER@DOMAIN.com\",\"run_as_user\":\"\",\"success_count\":303585,\"error_count\":0,\"last_success\":\"2016-11
-30T18:06:00.369454892-05:00\",\"last_error\":\"0001-01-01T00:00:00Z\",\"disabled\":false,\"tags\":{\"role\":\"background_processing:1\"}}}" query="run:job"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x48897c]

goroutine 45 [running]:
panic(0xbb9dc0, 0xc820010060)
        /Users/victorcoder/src/github.com/mxcl/homebrew/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/victorcoder/dkron/dkron.(*AgentCommand).eventLoop(0xc82004e480)
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:490 +0x1abc
created by github.com/victorcoder/dkron/dkron.(*AgentCommand).Run
        /Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:298 +0x362
```

It goes on like that a few more times, each with the agent restarting and then immediately dying after running the job.

In syslog, I see this:

```
Dec  1 13:53:00 ip-10-0-16-245 kernel: [13269.011886] init: dkron main process (19088) terminated with status 2
Dec  1 13:53:00 ip-10-0-16-245 kernel: [13269.011898] init: dkron main process ended, respawning
Dec  1 13:53:00 ip-10-0-16-245 kernel: [13269.255068] init: dkron main process (19108) terminated with status 2
Dec  1 13:53:00 ip-10-0-16-245 kernel: [13269.255080] init: dkron main process ended, respawning
Dec  1 13:53:00 ip-10-0-16-245 kernel: [13269.312429] init: dkron main process (19118) terminated with status 2
Dec  1 13:53:00 ip-10-0-16-245 kernel: [13269.312440] init: dkron main process ended, respawning
```

but I can see the dkron agent process running. Any ideas?

**Comment by victorcoder** [comment]
I'm pretty sure this has something to do with the structure of the data in the store.

Could you try to:

1. With dkron stopped, edit the job using consul API/GUI and set `disabled: true`
2. Start dkron and setup a new job

See if it still crashes.

If it works well, then:

1. Remove all past executions using consul API/GUI
2. Set `disabled: false` and start dkron

See what happens

**Comment by greggilbert** [comment]
So I did this:

1. Brought up a new instance with 0.9.1 on it
2. Gave the new instance a different role and key
3. Registered a new task with that role

and now it's running without any problems. So yeah, I guess the issue is weird data in there. I'm inclined to abandon the previous task and switch over to a new one.

**Comment by greggilbert** [comment]
Update: I'm not sure how related this is to everything else, but I'm seeing a lot more `Received execution done for a deleted job` in the logs. Most of the executions don't have a `finished_at` timestamp, but the job itself has the correct `last_success`. Any ideas?

Here are debug logs:
```
time="2016-12-07T15:41:22-05:00" level=debug msg="scheduler: Run job" job="worker_queue" node=ip-10-100-15-189 schedule="@every 1m"
time="2016-12-07T15:41:22-05:00" level=debug msg="store: Retrieved job from datastore" job="worker_queue" node=ip-10-100-15-189
time="2016-12-07T15:41:22-05:00" level=debug msg="agent: Filtered nodes to run: [ip-10-100-15-189]" node=ip-10-100-15-189
time="2016-12-07T15:41:22-05:00" level=debug msg="agent: Filtered tags to run: map[role:background_processing:1]" node=ip-10-100-15-189
time="2016-12-07T15:41:22-05:00" level=debug msg="agent: Sending query" job_name="worker_queue" json="{\"execution\":{\"job_name\":\"worker_queue\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1481143282000274422,\"attempt\":1},\"rpc_addr\":\"10.100.15.189:6868\"}" node=ip-10-100-15-189 query="run:job"
time="2016-12-07T15:41:22-05:00" level=debug msg="agent: Received event" event="query: run:job" node=ip-10-100-15-189
time="2016-12-07T15:41:22-05:00" level=debug msg="agent: Running job" at=355011 node=ip-10-100-15-189 payload="{\"execution\":{\"job_name\":\"worker_queue\",\"started_at\":\"0001-01-01T00:00:00Z\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"group\":1481143282000274422,\"attempt\":1},\"rpc_addr\":\"10.100.15.189:6868\"}" query="run:job"
time="2016-12-07T15:41:22-05:00" level=info msg="agent: Starting job" job="worker_queue" node=ip-10-100-15-189
time="2016-12-07T15:41:22-05:00" level=debug msg="agent: Received ack" from=ip-10-100-15-189 node=ip-10-100-15-189 query="run:job"
time="2016-12-07T15:41:22-05:00" level=debug msg="rpc: Received GetJob" job="worker_queue" node=ip-10-100-15-189
time="2016-12-07T15:41:22-05:00" level=debug msg="store: Retrieved job from datastore" job="worker_queue" node=ip-10-100-15-189
time="2016-12-07T15:41:22-05:00" level=debug msg="agent: GetJob by RPC" command="/cron-worker-queue.sh" node=ip-10-100-15-189
time="2016-12-07T15:41:22-05:00" level=debug msg="agent: Received response" from=ip-10-100-15-189 node=ip-10-100-15-189 query="run:job" response="{\"job_name\":\"worker_queue\",\"started_at\":\"2016-12-07T15:41:22.006612531-05:00\",\"finished_at\":\"0001-01-01T00:00:00Z\",\"node_name\":\"ip-10-100-15-189\",\"group\":1481143282000274422,\"attempt\":1}"
time="2016-12-07T15:41:22-05:00" level=debug msg="store: Setting key" execution=1481143282006612531-ip-10-100-15-189 job="worker_queue" node=ip-10-100-15-189
time="2016-12-07T15:41:22-05:00" level=debug msg="proc: Command output" node=ip-10-100-15-189 output=
time="2016-12-07T15:41:22-05:00" level=debug msg="proc: Received ack" from=ip-10-100-15-81 node=ip-10-100-15-189 query="rpc:config"
time="2016-12-07T15:41:22-05:00" level=debug msg="proc: Received response" from=ip-10-100-15-81 node=ip-10-100-15-189 payload="10.100.15.81:6868" query="rpc:config"
time="2016-12-07T15:41:25-05:00" level=debug msg="agent: Done receiving acks and responses" node=ip-10-100-15-189 query="run:job"
time="2016-12-07T15:41:25-05:00" level=debug msg="proc: Done receiving acks and responses" node=ip-10-100-15-189 query="rpc:config"
time="2016-12-07T15:41:25-05:00" level=warning msg="rpc: Error calling ExecutionDone" error="rpc: Received execution done for a deleted job." node=ip-10-100-15-189
time="2016-12-07T15:41:25-05:00" level=error msg="agent: Error invoking job command" error="rpc: Received execution done for a deleted job." node=ip-10-100-15-189
```

**Comment by greggilbert** [comment]
I think I solved this by changing the Consul service that the instance was registered in (e.g. `foo` -> `foo2`), and also by changing `"join"` in the dkron config from the previous service to a new one. So I think we're all good from here, but if we could leave this ticket open for a few more days just so I can double confirm, that'd be great.

Thanks a lot for your help on this - much appreciated!

**Comment by greggilbert** [comment]
Alright, gonna close this one out. Thanks again for all your help - you've built something really great here.
