### ISSUE TITLE
panic when key not found in the store

### ISSUE THREAD

**Issue by ProPheT777** [victorcoder/dkron#386]
Hey, 

For example delete a job from the UI while job is playing / failing in my case

here the trace : 

```
INFO[2018-05-26T17:22:32Z] agent: Dkron agent starting                   node=e903d7035a06
INFO[2018-05-26T17:22:32Z] agent: joining: [dkron] replay: true          node=e903d7035a06
INFO[2018-05-26T17:22:32Z] agent: joined: 1 nodes                        node=e903d7035a06
INFO[2018-05-26T17:22:32Z] agent: Listen for events                      node=e903d7035a06
INFO[2018-05-26T17:22:32Z] agent: Starting job                           job=vacuum_worker_timedout node=e903d7035a06
WARN[2018-05-26T17:22:32Z] rpc: Error calling GetJob                     error="Key not found in store" node=e903d7035a06
ERRO[2018-05-26T17:22:32Z] agent: Error on rpc.GetJob call               error="Key not found in store" node=e903d7035a06
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbcc4f0]

goroutine 60 [running]:
github.com/victorcoder/dkron/dkron.(*Agent).eventLoop(0xc42008b260)
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:431 +0x13e0
created by github.com/victorcoder/dkron/dkron.(*Agent).Start
	/Users/victorcoder/src/github.com/victorcoder/dkron/dkron/agent.go:91 +0x180
```

**Comment by victorcoder** [comment]
Related to https://github.com/victorcoder/dkron/issues/384
